### ISSUE TITLE
Unable to actually use the mod.

### ISSUE THREAD

**Issue by VonBunBun** [lsrom/superflatbiomes#4]
I fixed all the issues of having the wrong mod versions, but when I try to use it, it just gives me error code -1?

**Comment by lsrom** [comment]
Not sure what could be the issue, there should be a stacktrace from the launcher with more info.

**Comment by VonBunBun** [comment]
It says java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'superflatbiomes'!

**Comment by VonBunBun** [comment]
![Screenshot 2023-10-12 153107.png](https://github.com/lsrom/superflatbiomes/assets/147319854/6c24109d-bf66-4046-bd57-1c519a2eb9e2)

Here is the mod folder

**Comment by VonBunBun** [comment]
I'm just a moron, I just had it in the wrong version, I had it in 1.19.4

**Comment by lsrom** [comment]
Sorry, I was taking a break from Minecraft, glad you got it working :)
